name = "test-r2"
main = "dist/worker.js"
compatibility_date = "2022-07-29"
usage_model = "bundled"
account_id = ""

r2_buckets = [
  { binding = 'BUCKET', bucket_name = 'test-bucket', preview_bucket_name = 'dev-test' },
]

[build]
command = "zig build && npm run esbuild"
watch_dir = [
  "test",
  "src",
  "lib"
] # Defaults to "test" if command set